import { Cpu, CpuDevices } from "./cpu";

export const CPUS: Cpu[] = [
 {
    id: 1,
    componentId: 'CPU1',
    name: 'Intel 4004',
    family: 'Intel',
    programMemory: '4KB',
    ramMemory: '640 bytes',
    clockSpeed: '740Khz',
    power: '0.45W',
    wordSize: '4 bits',
    process: '10000nm',
    description: 'Desarrollado para calculadoras de la marca Busicom, se instaló en máquinas de Pinball y fue candidato a instalarse en la nave espacial Pioneer 10. Existe una réplica funcional de 41x58cm en el Intel Museum de California.',
    years: '1971-1981',
    passmark: '',
    periodId: 1,
    transistors: 2300,
    price: '1800-3600$',
    performance: 0.03,
    devices: [CpuDevices.desktop, CpuDevices.portable],
    imgNames: ['4004-1.jpg', '4004-2.jpg', '4004-3.jpg']
},
 {
    id: 2,
    componentId: 'CPU2',
    name: 'Intel 8008',
    family: 'Intel',
    programMemory: '16KB',
    ramMemory: '',
    clockSpeed: '200-800Khz',
    power: '1W',
    wordSize: '8 bits',
    process: '10000nm',
    description: 'Sucesor de 8 bits del 4004. Creado para el ordenador DataPoint 2200, pero no usado por su bajo rendimiento. Usado en terminales, embotelladoras, robots y computadoras simples. Tenía un juego de instrucciones propio.',
    years: '1972-1983',
    passmark: '',
    periodId: 1,
    transistors: 3500,
    price: '120$',
    performance: 0.016,
    devices: [CpuDevices.desktop],
    imgNames: ['8008-1.jpg', '8008-2.jpg', '8008-3.jpg']
},
 {
    id: 3,
    componentId: 'CPU3',
    name: 'Intel 4040',
    family: 'Intel',
    programMemory: '8KB',
    ramMemory: '640 bytes',
    clockSpeed: '500-740Khz',
    power: '0.6W',
    wordSize: '4 bits',
    process: '10000nm',
    description: 'Uno de los dos sucesores del 4004 junto con el 8008, igualmente de 4 bits, pero que incorporaba nuevas instrucciones, registros y soporte para interrupciones hardware.',
    years: '1974-1981',
    passmark: '',
    periodId: 1,
    transistors: 3000,
    price: '200$',
    performance: 0.03,
    devices: [CpuDevices.desktop, CpuDevices.portable],
    imgNames: ['4040-1.jpg', '4040-2.jpg', '4040-3.jpg']
}
];